In [1]:
from HW1.gradient_descent import gradient_descent, linear_step_chooser
from HW1.one_demensional import dichotomy, golden, fib
import numpy as np

In [2]:
def f(arg):
    return np.sum(arg ** 2)

In [3]:
def grad(arg):
    return 2 * arg

In [4]:
ans, trace = gradient_descent(f, grad, np.array([100, 200]), linear_step_chooser(golden), stop_criterion='grad')

In [5]:
ans

array([-4.77135918e-15, -9.54271835e-15])

In [6]:
trace

[array([100, 200]),
 array([0.00040557, 0.00081115]),
 array([-9.78295861e-10, -1.95659172e-09]),
 array([-4.77135918e-15, -9.54271835e-15])]